# Generated by Django 2.0.5 on 2018-05-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinAge', models.IntegerField(default=1)),
                ('MaxAge', models.IntegerField(default=99)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.TextField(default='')),
                ('TimeCreated', models.BigIntegerField(default=0)),
                ('StartTime', models.BigIntegerField(default=0)),
                ('EndTime', models.BigIntegerField(default=0)),
                ('GuestsLimit', models.IntegerField(default=4)),
                ('EventType', models.IntegerField(choices=[(0, 'PublicEvent'), (1, 'PrivateEvent')], default=0)),
                ('Latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('LocationName', models.TextField(default='')),
                ('Description', models.TextField(default=0.0)),
                ('GoogleMapsURL', models.TextField(default=0.0)),
                ('AgeRestriction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restserver.AgeRestriction')),
            ],
        ),
        migrations.CreateModel(
            name='MeetUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Token', models.TextField(default='')),
                ('FirstName', models.TextField(default='')),
                ('LastName', models.TextField(default='')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('PhoneNumber', models.TextField(default='')),
                ('Description', models.TextField(default='')),
                ('PhotoURL', models.TextField(default='')),
                ('Rating', models.DecimalField(decimal_places=10, default=3.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='CreatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_of', to='restserver.MeetUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='GuestsIds',
            field=models.ManyToManyField(related_name='guest_of', to='restserver.MeetUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='QrCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restserver.QrCode'),
        ),
    ]
